### ISSUE TITLE
learn: Hasura backend tutorial [remote-schemas]

### ISSUE THREAD

**Issue by waptik** [hasura/learn-graphql#5] opened 2019-09-13 14:00 UTC
In [remote-schemas](https://learn.hasura.io/graphql/hasura/custom-business-logic/1-remote-schemas), the demo app is not working as it should. On [glitch](https://auth0-hasura-remote-schema.glitch.me/), this query

```js
# Write your query or mutation here
query {
  auth0 {
    email,
    picture
  }
}
```
displays some errors.

**Comment by alizhdanov** [comment] 2019-10-16 16:37
Hey @praveenweb, I see `hacktoberfest` tag. But what exactly should be done? Just add more human-readable error, that  `Authorization` token is missing? It should be helpful for beginners.

**Comment by nik72619c** [comment] 2019-10-26 12:41
Yes, I'd love to take this one up. Kindly guide me with this if this is still open to take it !

**Comment by praveenweb** [comment] 2020-06-02 14:25
Unable to reproduce this. Closing this now.

**Closed by praveenweb** 2020-06-02 14:25 UTC
Labels: backend, hacktoberfest
